### ISSUE TITLE
Issues with Burp Extension

### ISSUE THREAD

**Issue by kevcody-zz** [v-p-b/oracle_forms#1] opened 2015-09-22 17:33 UTC
After build and integration of the Burp Extension, I am seeing Java exceptions in the Java output of java.io EOF exception and java.lang.IllegalArgumentException. The ANT build process was followed and the first encrypted string of text (server information) is decrypted; however, no text after the first request is readable. Any idea/suggestions in regard to editing the extension to overcome this hurdle?

**Comment by v-p-b** [comment] 2015-09-23 06:57
You can test message parsing with MessageTester that allows you to debug the parsing process step-by-step. You should add frmall.jar to the project of course and you can provide to Eclipse the JAD decompiled pseudocode as the source so you can see the internals of the parser too. 

If you can't come over the problem attach the debug output of the extension to this issue and I'll take a look.

**Comment by kevcody-zz** [comment] 2015-09-25 00:38
Clearing the Java Cache/Temp Files and re-opening a fresh Burp instance regained usage; however, eventually the extension seemed to loose sync again.  Also, there didn't seem to be a way to manually edit the text in the OracleForms (clear text) tab to allow manually editing.

**Comment by v-p-b** [comment] 2015-09-25 07:35
"Clearing the Java Cache/Temp Files and re-opening a fresh Burp instance regained usage; however, eventually the extension seemed to loose sync again." 

These definitely seem like bugs. Can you provide the debug output?

"Also, there didn't seem to be a way to manually edit the text in the OracleForms (clear text) tab to allow manually editing." 

This is by design to prevent loosing sync. Maybe this can be improved in the future as a new feature.

**Comment by wflk** [comment] 2015-10-07 13:59
I cannot see any decrypted responses. Does it suppose to decrypt responses ?

**Comment by v-p-b** [comment] 2015-10-07 14:06
@wflk Yes it should decrypt messages, but you have to enable the extension before the key exchange happens. If you provide some debug output I'll probably be able to help more. 

Also, please open new tickets for separate issues!

**Comment by wflk** [comment] 2015-10-08 06:13
I thought it might be related to this issue as well.

It finds the keys and able to decrypt requests, but for responses I always getting empty.

Oracle Forms Tester loaded
Found GDay!
Found GDay! 5c0a85a8
Found Mate! 000064a9
RC4 Key: 854aae0a06

<...>

Response:
Encrypted Response: 
Body: 0 byte(s)
Request:
Encrypted Request: 699d5f9a9f9697cdb62d3184
ebece2c756c143f716878443869a369d3c1851f15268156ad1374133a580bbb2
Body: 12 byte(s)
Property 0: 137 Type: 9
--- Value: java.awt.Point[x=1879,y=985]
Message OK

## 100006a089075703d9f0f001

Response:
Encrypted Response: 
Body: 0 byte(s)
Request:
Encrypted Request: 6bdedeb21dcab317
73f649f9e4885627ef999551ba7eded044155bab44044779abb85bdb2cc59cae
Body: 8 byte(s)
Property 0: 517 Type: 12
Message OK

## 1000018205f0f001

Response:
Encrypted Response: 
Body: 0 byte(s)
Request:
Encrypted Request: 8b0b4021158708cc
5cc20afc7f9893b0eeaed6abab77a25f1314930a5df3576d929d8b534ad36880
Body: 8 byte(s)
Property 0: 517 Type: 12
Message OK

## 1000018205f0f001

Response:
Encrypted Response: 
Body: 0 byte(s) 

Moreover, I cannot see OracleForms tab in response tab in Burp.

**Comment by v-p-b** [comment] 2015-10-08 14:21
The debug output shows that the response bodies are 0 bytes long that can be normal. Do you see any encrypted content in the respective responses?

**Comment by wflk** [comment] 2015-10-09 07:54
Yes, I see encrypted content, but on debug log it still shows me 0 byte response.

For example (attached screenshot) the first request after finding RC4 key. There is encrypted content and decrypted in Oracle Forms tab.

![screen](https://cloud.githubusercontent.com/assets/15015797/10388528/8e10dc0c-6e73-11e5-9e59-2689fa35681e.PNG)

Meanwhile in the response I can see a lot of encrypted content, but there is no Oracle Forms tab and in the debug logs it still says

Response:
Encrypted Response: 
Body: 0 byte(s)

![screen2](https://cloud.githubusercontent.com/assets/15015797/10388561/d197a78a-6e73-11e5-88bb-fe0d29514b98.PNG)

It seems the plugin just cannot find encrypted responses.

**Comment by v-p-b** [comment] 2015-10-12 11:50
It seems to be the problem is that your application behaves differently than the ones I've tested so far. The extension currently expects the encrypted body to be sent back by a double HTTP header, while your app only sends one. You can see this implemented here:

https://github.com/v-p-b/oracle_forms/blob/master/OracleFormsTester/src/burp/BurpExtender.java#L199

It would be nice to know what setting makes the difference. The issue could probably be worked around by replacing line #199 and #200 with

```
innerMsg=msg;
```

**Comment by v-p-b** [comment] 2015-10-12 12:19
Closing this issue since it has a too generic title and it already contains different problems. If followup is needed please open a new ticket with proper title.

**Closed as completed by v-p-b** 2015-10-12 12:19 UTC
